---
title: "Thesis Graphs"
author: "Kaitlyn Li"
date: "11/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse); theme_set(theme_light())
library(googlesheets4)
library(viridis)
```

#
```{r}
url <- "https://docs.google.com/spreadsheets/d/1JN0UHSJSlPWP07gGkodhEuOzFkuukClbuDjI7rDcokc/edit?usp=sharing"
streaks <- read_sheet(ss = url,
                     sheet = "Streaks")
srl_dils <- read_sheet(ss = url,
                     sheet = "Serial_Dilutions")
nming_dils <- read_sheet(ss = url,
                     sheet = "Normalizing_Dilutions")
nmed_dils <- read_sheet(ss = url,
                     sheet = "Normalized_Dilutions")

```

```{r eval = F}
ggplot(streaks, aes(x = Time, y = Colonies, color = Strain)) +
  geom_jitter() +
  geom_smooth(se = F, method = lm) +
  scale_color_viridis(discrete=TRUE)  +
  theme(text=element_text(family="serif"))
  
ggplot(srl_dils, aes(x = Time, y = CFU_mL, color = Strain)) +
  geom_jitter() +
  geom_smooth(se = F, method = lm)+
  scale_color_viridis(discrete=TRUE)  +
  theme(text=element_text(family="serif"))
```

```{r eval = F}
uv_sum <- streaks %>%
  group_by(Strain, Time) %>%
  summarise(mean = mean(Colonies),
            median = median(Colonies),
            sd = sd(Colonies)
            )
uv_sum
```
```{r eval = F}
ggplot(uv_sum, aes(x = Time, y = median, color = Strain)) +
  geom_jitter() +
  geom_smooth(se = F, method = lm)+
  scale_color_viridis(discrete=TRUE)  +
  theme(text=element_text(family="serif"))
```
```{r streaks_end eval = F}
final_uvs <- streaks %>%
  filter(Strain == c("DRAD", "1F1", "1F5", "DH5A"))
ggplot(final_uvs, aes(x = Time, y = Colonies, color = Strain)) +
  geom_jitter() +
  geom_smooth(se = F, method = lm)+
  scale_color_viridis(discrete=TRUE)  +
  theme(text=element_text(family="serif"))
  
pcr_strains <- streaks %>%
  filter(Strain == c("1F1", "1F5", "1FH2", "CM1"))
ggplot(pcr_strains, aes(x = Time, y = Colonies, color = Strain)) +
  geom_jitter() +
  geom_smooth(se = F, method = lm)+
  scale_color_viridis(discrete=TRUE)  +
  theme(text=element_text(family="serif"))
  
  
```



```{r p_survival}
sixtys_uv <- srl_dils %>%
  filter(Time == 60) %>%
  group_by(Strain, Set) %>%
  summarise(CFU_60 = mean(CFU_mL))

zeros_uv <- srl_dils %>%
  filter(Time == 0) %>%
  group_by(Strain, Set) %>%
  summarise(CFU_0 = mean(CFU_mL))

sz_uv <- left_join(zeros_uv, sixtys_uv)

sz_uv <- sz_uv %>%
  mutate(p_survival = CFU_60/CFU_0)

write.csv(sz_uv,here::here("data", "sz_uv.csv"), row.names = FALSE)

ggplot(sz_uv, aes(x = Strain, y = log(p_survival), color = Strain)) +
  geom_boxplot() +
  labs(title = "Percent Survival of Strains in UV irradiation",
       y = "Log10 of Percent Survival")+
  scale_color_viridis(discrete=TRUE)  +
  theme(text=element_text(family="serif"))

ggplot(sz_uv, aes(x = Strain, y = p_survival, color = Strain)) +
  geom_boxplot() +
  labs(title = "Percent Survival of Strains in UV irradiation",
       y = "Percent Survival")+
  scale_color_viridis(discrete=TRUE)  +
  theme(text=element_text(family="serif"))
```

```{r t_tests}
dh5a <- sz_uv %>%
  filter(Strain == 	"DH5A")

drad <- sz_uv %>%
  filter(Strain == 	"DRAD")

f5 <- sz_uv %>%
  filter(Strain == 	"1F5")

fh2 <- sz_uv %>%
  filter(Strain == 	"1FH2")

cm1 <- sz_uv %>%
  filter(Strain == 	"CM1")


t.test(x = sz_uv$CFU_0, y = sz_uv$CFU_60) #all strains
t.test(x = dh5a$CFU_0, y = dh5a$CFU_60) #dh5a
t.test(x = drad$CFU_0, y = drad$CFU_60) #drad
t.test(x = f5$CFU_0, y = f5$CFU_60) #f5
t.test(x = cm1$CFU_0, y = cm1$CFU_60) #cm1
t.test(x = fh2$CFU_0, y = fh2$CFU_60) #fh2
```

```{r normalizing}
normalizing <-nming_dils %>%
  group_by(Strain)%>%
  summarise(mean = mean(CFU_mL)) %>%
  arrange(mean) %>%
  mutate(ul_culture = mean[1]/mean*1000,
         ul_PBS = 1000-ul_culture)
normalizing


```


```{r normalized}
n_sixtys_uv <- nmed_dils %>%
  filter(Time == 60) %>%
  group_by(Strain, Set) %>%
  summarise(CFU_60 = mean(CFU_mL))

n_zeros_uv <- nmed_dils %>%
  filter(Time == 0) %>%
  group_by(Strain, Set) %>%
  summarise(CFU_0 = mean(CFU_mL))

n_sz_uv <- left_join(n_zeros_uv, n_sixtys_uv)

n_sz_uv <- n_sz_uv %>%
  mutate(p_survival = CFU_60/CFU_0)

write.csv(n_sz_uv,here::here("data", "n_sz_uv.csv"), row.names = FALSE)

ggplot(n_sz_uv, aes(x = Strain, y = log(p_survival), color = Strain)) +
  geom_boxplot() +
  labs(title = "Percent Survival of Normalized Strains in UV irradiation",
       y = "Log10 of Percent Survival")+
  scale_color_viridis(discrete=TRUE)  +
  theme(text=element_text(family="serif"))

ggplot(n_sz_uv, aes(x = Strain, y = p_survival, color = Strain)) +
  geom_boxplot() +
  labs(title = "Percent Survival of Normalized Strains in UV irradiation",
       y = "Percent Survival")+
  scale_color_viridis(discrete=TRUE)  +
  theme(text=element_text(family="serif"))
```

```{r n_t_tests}
n_dh5a <- n_sz_uv %>%
  filter(Strain == 	"DH5A")

n_drad <- n_sz_uv %>%
  filter(Strain == 	"DRAD")

n_f5 <- n_sz_uv %>%
  filter(Strain == 	"1F5")

n_fh2 <- n_sz_uv %>%
  filter(Strain == 	"1FH2")

n_cm1 <- n_sz_uv %>%
  filter(Strain == 	"CM1")


t.test(x = n_sz_uv$CFU_0, y = n_sz_uv$CFU_60) #all strains
t.test(x = n_dh5a$CFU_0, y = n_dh5a$CFU_60) #dh5a
t.test(x = n_drad$CFU_0, y = n_drad$CFU_60) #drad
t.test(x = n_f5$CFU_0, y = n_f5$CFU_60) #f5
t.test(x = n_cm1$CFU_0, y = n_cm1$CFU_60) #cm1
t.test(x = n_fh2$CFU_0, y = n_fh2$CFU_60) #fh2
```

```{r}
t.test(x = n_dh5a$p_survival, y = n_drad$p_survival) #dh5a
t.test(x = n_dh5a$p_survival, y = n_f5$p_survival) #drad
t.test(x = n_dh5a$p_survival, y = n_cm1$p_survival) #f5
t.test(x = n_dh5a$p_survival, y = n_fh2$p_survival) #cm1
t.test(x = n_drad$p_survival, y = n_f5$p_survival) #drad
t.test(x = n_drad$p_survival, y = n_cm1$p_survival) #f5
t.test(x = n_drad$p_survival, y = n_fh2$p_survival) #cm1
t.test(x = n_f5$p_survival, y = n_cm1$p_survival) #f5
t.test(x = n_f5$p_survival, y = n_fh2$p_survival) #cm1
t.test(x = n_cm1$p_survival, y = n_fh2$p_survival) #cm1
```


```{r}
DH5A_z_nuv <- nmed_dils %>%
  filter(Time == 0) %>%
  group_by(Strain, Set)%>%
  filter(Strain == "DH5A") %>%
  select(-Time)
DH5A_z_nuv

write.csv(DH5A_z_nuv, here::here("data", "DH5A_z_nuv.csv"), row.names = FALSE)
```

```{r anova}
library(ggpubr)
library(broom)
library(AICcmodavg)

combined_szs <- n_sz_uv %>%
  mutate(normalized = TRUE)
temp_sz_uv <- sz_uv %>%
  mutate(normalized = FALSE)
combined_szs <- bind_rows(combined_szs, temp_sz_uv)



n_one_way <- aov(p_survival ~ Strain, data = n_sz_uv)
one_way <- aov(p_survival ~ Strain, data = sz_uv)
c_one_way <- aov(p_survival ~ Strain, data = combined_szs)
one_way <- aov(p_survival ~ Strain, data = sz_uv)
two_way <- aov(p_survival ~ Strain + normalized, data = combined_szs)
interaction <- aov(p_survival ~ Strain * normalized, data = combined_szs)
blocking <- aov(p_survival ~ Strain + normalized + Set, data = combined_szs)

model.set <- list(n_one_way, one_way, c_one_way, two_way, interaction, blocking)
model.names <- c("n_one_way", "one_way","c_one_way", "two_way", "interaction", "blocking")

aictab(model.set, modnames = model.names)
# model with the lowest AIC score (listed first in the table) is the best fit for the data

par(mfrow=c(2,2))
plot(one_way)
par(mfrow=c(1,1))


par(mfrow=c(2,2))
plot(c_one_way)
par(mfrow=c(1,1))

tukey_two_way <- TukeyHSD(two_way)
tukey_two_way

summary(n_one_way)
summary(one_way)

tukey_n_one_way<-TukeyHSD(n_one_way)
tukey_n_one_way
tukey_one_way<-TukeyHSD(one_way)
tukey_one_way

plot(tukey_n_one_way, las = 1)
plot(tukey_one_way, las = 1)
```

